apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugonna-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ugonna-springboot
  template:
    metadata:
      labels:
        app: ugonna-springboot
    spec:
      containers:
        - name: springboot
          image:elvindavin4u/ugonna-docker-demo:ugonna-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ugonna-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ugonna-springboot
